### ISSUE TITLE
2 issues; .NET 6 desktop runtime requirement not obvious, Failed to start up if debug.log is missing

### ISSUE THREAD

**Issue by Benc85** [DW2MC/DW2ModLoader#3]
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'WindowsBase, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'WindowsBase, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Program.Main(String[] args)

**Comment by Benc85** [comment]
Running the new DW2Net6Win.exe causes this issue.

**Comment by Tyler-IN** [comment]
I need some more details on this. Are you able to contact us on Discord?
I'd like to get your OS version and to know if you have .NET 6 installed.
I believe you may need to choose the middle option from
https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime where it
says "Run desktop apps"

**Comment by Benc85** [comment]
Yes, i'm about on discord. I'm running win 10, and have installed what you've suggested.

Running DW2Net6Win.exe now produces this error:

Created AppContainer isolated process 14368
DW2Net6Win v1.1.2
Unhandled exception. HarmonyLib.HarmonyException: Patching exception in method System.Void Xenko.Animations.AnimationUpdater::Update(Xenko.Engine.Entity entity, Xenko.Animations.AnimationClipResult result)
 ---> System.TypeInitializationException: The type initializer for 'HarmonyLib.HarmonySharedState' threw an exception.
 ---> System.NotSupportedException: Body-less method
   at MonoMod.Utils.DynamicMethodDefinition._CopyMethodToDefinition()
   at MonoMod.Utils.DynamicMethodDefinition.Reload()
   at MonoMod.Utils.DynamicMethodDefinition..ctor(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at HarmonyLib.HarmonySharedState..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at HarmonyLib.Harmony.PatchAll()
   at Program.Main(String[] args)

**Comment by Benc85** [comment]
Might this be an issue with the new 1.0.3.3 patch? I've just deleted all the recent DW2 Mod loader stuff and reinstalled version 1.1.0 (when i never had any issues), and its throwing the same error

**Comment by Tyler-IN** [comment]
Probably, I haven't worked with anything above v1.0.3.1 yet. I'll get to it
this evening.

**Comment by Benc85** [comment]
Ive just tried the new v1.2 and im getting this error now:

System.ArgumentException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
The path 'C:\Program Files\Steam\steamapps\common\Distant Worlds 2\debug.log' does not exist.
   at DW2Net6Win.Isolation.Windows.StartIsolatedProcess(String appContainerName, String path, String[] commandLineArguments, IEnumerable`1 capabilitySids, Boolean attachToCurrentProcess, IEnumerable`1 fileAccess, String workingDirectory)
   at Launcher.Run(String[] args)
=== === === === === === WARNING === === === === === ===
 Failed to create AppContainer isolation environment!
 You may need to run this executable as admin in order to
 run the game isolated. Without AppContainer isolation,
 it may be unsafe to run the game with modifications.
 If you wish to continue without isolation, press the
 [F5] key. The exception above has some clue as to why
 the failure occurred, it is likely that directory
 permissions are already more restricted than the
 launcher expected for the current user.
=== === === === === === WARNING === === === === === ===

              Press any key to exit.

Same error when run as admin. Pressing F5 enters the game, seemingly with V6 running, but with the isolation disabled.

Thanks for your continued work Tyler, your AMD fix single-handedly turned this game around for me :)

**Comment by Tyler-IN** [comment]
Ah, I'll see if I can fix that.

**Comment by Tyler-IN** [comment]
@Benc85 try the latest GitHub actions artifact and let me know if it works any better for you?

**Comment by Benc85** [comment]
I followed your advice and made a debug.log and the launcher worked flawlessly @tyler-in. I haven't had a chance to run the v1.2.1 release yet, but ill get back to you shortly if i have any issues.  Thanks for all the help mate

**Comment by Benc85** [comment]
Everything looks good Tyler. no issues with startup at all. Nice work
